modules/guestbook/models/Guestbook.php
<?php
namespace nitm\cms\modules\guestbook\models;

use Yii;
use nitm\cms\behaviors\CalculateNotice;
use nitm\cms\helpers\Mail;
use nitm\cms\models\Setting;
use nitm\cms\modules\guestbook\GuestbookModule;
use nitm\cms\validators\ReCaptchaValidator;
use nitm\validators\EscapeValidator;
use yii\helpers\Url;

class Guestbook extends \nitm\cms\db\ActiveRecord
{
    const STATUS_OFF = 0;
    const STATUS_ON = 1;
    const FLASH_KEY = 'eaysiicms_guestbook_send_result';

    public $reCaptcha;

    public static function tableName()
    {
        return 'cms_guestbook';
    }

    public function rules()
    {
        return [
            [['name', 'text'], 'required'],
            [['name', 'title', 'text'], 'trim'],
            [['name', 'title', 'text'], EscapeValidator::className()],
            ['email', 'email'],
            ['title', 'string', 'max' => 128],
            ['reCaptcha', ReCaptchaValidator::className(), 'on' => 'send', 'when' => function () {
                return GuestbookModule::setting('enableCaptcha');
            }],
        ];
    }

    public function beforeSave($insert)
    {
        if (parent::beforeSave($insert)) {
            if ($insert) {
                $this->ip = Yii::$app->request->userIP;
                $this->time = time();
                $this->new = 1;
                $this->status = GuestbookModule::setting('preModerate') ? self::STATUS_OFF : self::STATUS_ON;
            }
            return true;
        } else {
            return false;
        }
    }

    public function afterSave($insert, $changedAttributes)
    {
        parent::afterSave($insert, $changedAttributes);

        if ($insert) {
            $this->mailAdmin();
        }
    }

    public function attributeLabels()
    {
        return [
            'name' => Yii::t('nitm/cms', 'Name'),
            'title' => Yii::t('nitm/cms', 'Title'),
            'email' => 'E-mail',
            'text' => Yii::t('nitm/cms', 'Text'),
            'answer' => Yii::t('nitm/cms', 'Answer'),
            'reCaptcha' => Yii::t('nitm/cms', 'Anti-spam check')
        ];
    }

    public function behaviors()
    {
        return [
            'cn' => [
                'class' => CalculateNotice::className(),
                'callback' => function () {
                    return self::find()->where(['new' => 1])->count();
                }
            ]
        ];
    }

    public function mailAdmin()
    {
        if (!GuestbookModule::setting('mailAdminOnNewPost')) {
            return false;
        }
        return Mail::send(
            Setting::get('admin_email'),
            GuestbookModule::setting('subjectOnNewPost'),
            GuestbookModule::setting('templateOnNewPost'),
            [
                'post' => $this,
                'link' => Url::to($this->context->getUrl(['/admin/guestbook/a/view', 'id' => $this->primaryKey]), true)
            ]
        );
    }

    public function notifyUser()
    {
        return Mail::send(
            $this->email,
            GuestbookModule::setting('subjectNotifyUser'),
            GuestbookModule::setting('templateNotifyUser'),
            [
                'post' => $this,
                'link' => Url::to([GuestbookModule::setting('frontendGuestbookRoute')], true)
            ]
        );
    }
}

modules/guestbook/controllers/AController.php
<?php
namespace nitm\cms\modules\guestbook\controllers;

use Yii;
use yii\data\ActiveDataProvider;
use \nitm\cms\actions\ChangeStatusAction;
use \nitm\cms\actions\DeleteAction;
use \nitm\cms\components\Controller;
use \nitm\cms\models\Module;
use \nitm\cms\modules\guestbook\models\Guestbook;

class AController extends Controller
{
    public $modelClass = 'nitm\cms\modules\guestbook\models\Guestbook';
    public $new = 0;
    public $noAnswer = 0;

    public function actions()
    {
        return [
            'delete' => [
                'class' => DeleteAction::className(),
                'successMessage' => Yii::t('nitm/cms', 'Entry deleted')
            ],
            'on' => ChangeStatusAction::className(),
            'off' => ChangeStatusAction::className(),
        ];
    }

    public function init()
    {
        parent::init();

        $this->new = Yii::$app->getModule('admin')->activeModules['guestbook']->notice;
        $this->noAnswer = Guestbook::find()->where(['answer' => ''])->count();
    }

    public function actionIndex($className=null, $options=[])
    {
        $data = new ActiveDataProvider([
            'query' => Guestbook::find()->desc(),
        ]);

        return $this->render('index', [
            'data' => $data
        ]);
    }

    public function actionNoanswer()
    {
        $this->setReturnUrl();

        $data = new ActiveDataProvider([
            'query' => Guestbook::find()->where(['answer' => ''])->desc(),
        ]);
        return $this->render('index', [
            'data' => $data
        ]);
    }

    public function actionView($id)
    {
        $model = $this->findModel($id);

        if ($model->new > 0) {
            $model->new = 0;
            $model->update();
        }

        if (Yii::$app->request->post('Guestbook')) {
            $model->answer = trim(Yii::$app->request->post('Guestbook')['answer']);
            if ($model->save($model)) {
                if (Yii::$app->request->post('mailUser')) {
                    $model->notifyUser();
                }
                $this->flash('success', Yii::t('nitm/cms', 'Answer successfully saved'));
            } else {
                $this->flash('error', Yii::t('nitm/cms', 'Update error. {0}', $model->formatErrors()));
            }
            return $this->refresh();
        } else {
            return $this->render('view', [
                'model' => $model
            ]);
        }
    }

    public function actionViewall()
    {
        Guestbook::updateAll(['new' => 0]);
        $module = Module::findOne(['name' => 'guestbook']);
        $module->notice = 0;
        $module->save();

        $this->flash('success', Yii::t('nitm/cms', 'Guestbook updated'));

        return $this->back();
    }

    public function actionSetnew($id)
    {
        $model = $this->findModel($id);

        $model->new = 1;
        if ($model->update()) {
            $this->flash('success', Yii::t('nitm/cms', 'Guestbook updated'));
        } else {
            $this->flash('error', Yii::t('nitm/cms', 'Update error. {0}', $model->formatErrors()));
        }
        return $this->redirect($this->getReturnUrl(['/admin/' . $this->module->id]));
    }
}

modules/guestbook/controllers/SendController.php
<?php
namespace nitm\cms\modules\guestbook\controllers;

use Yii;
use \nitm\cms\modules\guestbook\models\Guestbook as GuestbookModel;

class SendController extends \yii\web\Controller
{
    public function actionIndex($className=null, $options=[])
    {
        $model = new GuestbookModel;
        $model->scenario = 'send';
        $request = Yii::$app->request;

        if ($model->load($request->post())) {
            $returnUrl = $model->save() ? $request->post('successUrl') : $request->post('errorUrl');
            return $this->redirect($returnUrl);
        } else {
            return $this->redirect(Yii::$app->request->baseUrl);
        }
    }
}

modules/guestbook/views/a/_menu.php
<?php
use yii\helpers\Url;
use nitm\helpers\ArrayHelper;

$viewClass = @$viewClass ?: 'nav nav-pills';

$action = ArrayHelper::getValue($this, 'context.action.id', 'index');
$module = ArrayHelper::getValue($this, 'context.module.id', 'guestbook');

$backTo = null;
$indexUrl = Url::to(['/admin/'.$module]);
$noanswerUrl = Url::to(['/admin/'.$module.'/a/noanswer']);

if ($action === 'view') {
    $returnUrl = $this->context->getReturnUrl(['/admin/'.$module]);

    if (strpos($returnUrl, 'noanswer') !== false) {
        $backTo = 'noanswer';
        $noanswerUrl = $returnUrl;
    } else {
        $backTo = 'index';
        $indexUrl = $returnUrl;
    }
}
?>
<ul class="<?=$viewClass?>">
    <li <?= ($action === 'index') ? 'class="active"' : '' ?>>
        <a href="<?= $indexUrl ?>">
            <?php if ($backTo === 'index') : ?>
                <i class="fa fa-chevron-left font-12"></i>
            <?php endif; ?>
            <?= Yii::t('nitm/cms', 'All') ?>
        </a>
    </li>
    <li <?= ($action === 'noanswer') ? 'class="active"' : '' ?>>
        <a href="<?= $noanswerUrl ?>">
            <?php if ($backTo === 'noanswer') : ?>
                <i class="fa fa-chevron-left font-12"></i>
            <?php endif; ?>
            <?= Yii::t('nitm/cms', 'No answer') ?>
            <?php if ($this->context->noAnswer > 0) : ?>
                <span class="badge"><?= $this->context->noAnswer ?></span>
            <?php endif; ?>
        </a>
    </li>
    <li class="pull-right">
        <?php if ($action === 'view') : ?>
            <a href="<?= Url::to(['/admin/'.$module.'/a/setnew', 'id' => Yii::$app->request->get('id')]) ?>" class="text-warning"><span class="fa fa-eye-close"></span> <?= Yii::t('nitm/cms', 'Mark as new') ?></a>
        <?php else : ?>
            <a href="<?= Url::to(['/admin/'.$module.'/a/viewall']) ?>" class="text-warning"><span class="fa fa-eye-open"></span> <?= Yii::t('nitm/cms', 'Mark all as viewed') ?></a>
        <?php endif; ?>
    </li>
</ul>

modules/guestbook/views/a/index.php
<?php
use yii\helpers\Html;
use yii\helpers\StringHelper;
use yii\helpers\Url;
use \nitm\cms\modules\guestbook\models\Guestbook;

$this->title = Yii::t('nitm/cms', 'Guestbook');

$module = $this->context->module->id;
?>

<?= $this->render('_menu') ?>

<?php if($data->count > 0) : ?>
    <table class="table table-hover">
        <thead>
            <tr>
                <?php if(IS_ROOT) : ?>
                    <th width="50">#</th>
                <?php endif; ?>
                <th><?= Yii::t('nitm/cms', $this->context->module->settings['enableTitle'] ? 'Title' : 'Text') ?></th>
                <th width="150"><?= Yii::t('nitm/cms', 'Date') ?></th>
                <th width="100"><?= Yii::t('nitm/cms', 'Answer') ?></th>
                <th width="100"><?= Yii::t('nitm/cms', 'Status') ?></th>
                <th width="30"></th>
            </tr>
        </thead>
        <tbody>
    <?php foreach($data->models as $item) : ?>
            <tr>
                <?php if(IS_ROOT) : ?>
                    <td><?= $item->primaryKey ?></td>
                <?php endif; ?>
                <td>
                    <?php if($item->new) : ?>
                        <span class="label label-warning">NEW</span>
                    <?php endif; ?>
                    <a href="<?= Url::to(['/admin/'.$module.'/a/view', 'id' => $item->primaryKey]) ?>">
                        <?= ($item->title != '') ? $item->title : StringHelper::truncate($item->text, 120, '...') ?>
                    </a>
                </td>
                <td><?= Yii::$app->formatter->asDatetime($item->time, 'short') ?></td>
                <td>
                    <?php if($item->answer != '') : ?>
                        <span class="text-success"><?= Yii::t('nitm/cms', 'Yes') ?></span>
                    <?php else : ?>
                        <span class="text-danger"><?= Yii::t('nitm/cms', 'No') ?></span>
                    <?php endif; ?>
                </td>
                <td class="status">
                    <?= Html::checkbox('', $item->status == Guestbook::STATUS_ON, [
                        'class' => 'switch',
                        'data-id' => $item->primaryKey,
                        'data-link' => Url::to(['/admin/'.$module.'/a']),
                    ]) ?>
                </td>
                <td class="control"><a href="<?= Url::to(['/admin/'.$module.'/a/delete', 'id' => $item->primaryKey]) ?>" class="fa fa-remove confirm-delete" title="<?= Yii::t('nitm/cms', 'Delete item') ?>"></a></td>
            </tr>
    <?php endforeach; ?>
        </tbody>
    </table>
    <?= yii\widgets\LinkPager::widget([
        'pagination' => $data->pagination
    ]) ?>
<?php else : ?>
    <p><?= Yii::t('nitm/cms', 'No records found') ?></p>
<?php endif; ?>

modules/guestbook/views/a/view.php
<?php
use yii\helpers\Html;
use \nitm\cms\modules\guestbook\models\Guestbook;

$this->title = Yii::t('nitm/cms', 'View post');
$this->registerCss('.guestbook-view dt{margin-bottom: 10px;}');
?>
<?= $this->render('_menu') ?>

<dl class="dl-horizontal guestbook-view">
    <dt><?= Yii::t('nitm/cms', 'Name') ?></dt>
    <dd><?= $model->name ?></dd>

    <?php if($this->context->module->settings['enableTitle']) : ?>
    <dt><?= Yii::t('nitm/cms', 'Title') ?></dt>
    <dd><?= $model->title ?></dd>
    <?php endif; ?>

    <?php if($this->context->module->settings['enableEmail']) : ?>
        <dt><?= Yii::t('nitm/cms', 'E-mail') ?></dt>
        <dd><?= $model->email ?></dd>
    <?php endif; ?>

    <dt>IP</dt>
    <dd><?= $model->ip ?> <a href="//freegeoip.net/?q=<?= $model->ip ?>" class="label label-info" target="_blank">info</a></dd>

    <dt><?= Yii::t('nitm/cms', 'Date') ?></dt>
    <dd><?= Yii::$app->formatter->asDatetime($model->time, 'medium') ?></dd>

    <dt><?= Yii::t('nitm/cms', 'Text') ?></dt>
    <dd><?= nl2br($model->text) ?></dd>
</dl>

<hr>
<h2><small><?= Yii::t('nitm/cms', 'Answer') ?></small></h2>

<?= Html::beginForm() ?>
    <div class="form-group">
        <?= Html::textarea('Guestbook[answer]', $model->answer, ['class' => 'form-control', 'style' => 'height: 250px']) ?>
    </div>
    <?php if($model->answer == '' && $model->email) : ?>
    <div class="checkbox">
        <label>
            <input type="checkbox" name="mailUser" value="1" checked> <?= Yii::t('nitm/cms', 'Notify user about answer') ?>
        </label>
    </div>
    <?php endif; ?>
    <?= Html::submitButton(Yii::t('nitm/cms', 'Save'), ['class' => 'btn btn-success send-answer']) ?>
<?= Html::endForm() ?>