modules/article/models/Category.php
<?php
namespace nitm\cms\modules\article\models;

class Category extends \nitm\cms\components\CategoryModel
{
    public static function tableName()
    {
        return 'cms_article_categories';
    }

    public function getItems()
    {
        return $this->hasMany(Item::className(), ['category_id' => 'id'])->sortDate();
    }

    public function afterDelete()
    {
        parent::afterDelete();

        foreach ($this->getItems()->all() as $item) {
            $item->delete();
        }
    }
}

modules/article/models/Item.php
<?php
namespace nitm\cms\modules\article\models;

use Yii;
use yii\behaviors\SluggableBehavior;
use \nitm\cms\behaviors\ImageFile;
use \nitm\cms\behaviors\SeoBehavior;
use \nitm\cms\behaviors\Taggable;
use \nitm\cms\models\Photo;
use \nitm\cms\modules\article\ArticleModule;
use yii\helpers\StringHelper;

class Item extends \nitm\cms\db\ActiveRecord
{
    const STATUS_OFF = 0;
    const STATUS_ON = 1;

    public static function tableName()
    {
        return 'cms_article_items';
    }

    public function rules()
    {
        return [
            [['text', 'title'], 'required'],
            [['title', 'short', 'text'], 'trim'],
            ['title', 'string', 'max' => 128],
            ['image_file', 'image'],
            [['category_id', 'views', 'time', 'status'], 'integer'],
            ['time', 'default', 'value' => time()],
            ['slug', 'match', 'pattern' => self::$SLUG_PATTERN, 'message' => Yii::t('nitm/cms', 'Slug can contain only 0-9, a-z and "-" characters (max: 128).')],
            ['slug', 'default', 'value' => null],
            ['status', 'default', 'value' => self::STATUS_ON],
            ['tagNames', 'safe']
        ];
    }

    public function attributeLabels()
    {
        return [
            'title' => Yii::t('nitm/cms', 'Title'),
            'category_id' => Yii::t('nitm/cms', 'Category'),
            'text' => Yii::t('nitm/cms', 'Text'),
            'short' => Yii::t('nitm/cms', 'Short'),
            'image_file' => Yii::t('nitm/cms', 'Image'),
            'time' => Yii::t('nitm/cms', 'Date'),
            'slug' => Yii::t('nitm/cms', 'Slug'),
            'tagNames' => Yii::t('nitm/cms', 'Tags'),
        ];
    }

    public function behaviors()
    {
        $behaviors = [
            'seoBehavior' => SeoBehavior::className(),
            'taggabble' => Taggable::className(),
            'sluggable' => [
                'class' => SluggableBehavior::className(),
                'attribute' => 'title',
                'ensureUnique' => true,
                'immutable' => ArticleModule::setting('itemSlugImmutable')
            ]
        ];
        if (ArticleModule::setting('articleThumb')) {
            $behaviors['imageFileBehavior'] = ImageFile::className();
        }

        return $behaviors;
    }

    public function getCategory()
    {
        return $this->hasOne(Category::className(), ['category_id' => 'id']);
    }

    public function getPhotos()
    {
        return $this->hasMany(Photo::className(), ['item_id' => 'item_id'])->where(['class' => self::className()])->sort();
    }

    public function beforeSave($insert)
    {
        if (parent::beforeSave($insert)) {
            $this->short = StringHelper::truncate(ArticleModule::setting('enableShort') ? $this->short : strip_tags($this->text), ArticleModule::setting('shortMaxLength'));

            return true;
        } else {
            return false;
        }
    }

    public function afterDelete()
    {
        parent::afterDelete();

        foreach ($this->getPhotos()->all() as $photo) {
            $photo->delete();
        }
    }
}

modules/article/controllers/AController.php
<?php
namespace nitm\cms\modules\article\controllers;

use \nitm\cms\components\CategoryController;

class AController extends CategoryController
{
    /** @var string  */
    public $categoryClass = 'nitm\cms\modules\article\models\Category';
    
    /** @var string  */
    public $modelClass = 'nitm\cms\modules\article\models\Category';

    /** @var string  */
    public $moduleName = 'article';
}

modules/article/controllers/ItemsController.php
<?php
namespace nitm\cms\modules\article\controllers;

use Yii;
use \nitm\cms\actions\ChangeStatusAction;
use \nitm\cms\actions\ClearImageAction;
use \nitm\cms\actions\DeleteAction;
use \nitm\cms\actions\SortByDateAction;
use \nitm\cms\components\Controller;
use \nitm\cms\modules\article\ArticleModule;
use \nitm\cms\modules\article\models\Category;
use \nitm\cms\modules\article\models\Item;
use yii\widgets\ActiveForm;

class ItemsController extends Controller
{
    public $modelClass = 'nitm\cms\modules\article\models\Item';
    public $categoryClass = 'nitm\cms\modules\article\models\Category';

    public function actions()
    {
        return [
            'delete' => [
                'class' => DeleteAction::className(),
                'successMessage' => Yii::t('nitm/cms', 'Article deleted')
            ],
            'clear-image' => ClearImageAction::className(),
            'up' => SortByDateAction::className(),
            'down' => SortByDateAction::className(),
            'on' => ChangeStatusAction::className(),
            'off' => ChangeStatusAction::className(),
        ];
    }

    public function actionIndex($id)
    {
        return $this->render('index', [
            'category' => $this->findCategory($id)
        ]);
    }

    public function actionCreate($id)
    {
        $category = $this->findCategory($id);

        $model = new Item([
            'category_id' => $id,
            'time' => time()
        ]);

        if ($model->load(Yii::$app->request->post())) {
            if (Yii::$app->request->isAjax) {
                Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
                return ActiveForm::validate($model);
            } else {
                if ($model->save()) {
                    $this->flash('success', Yii::t('nitm/cms', 'Article created'));
                    return $this->redirect(['/admin/'.$this->module->id.'/items/form/update', 'id' => $model->primaryKey]);
                } else {
                    $this->flash('error', Yii::t('nitm/cms', 'Create error. {0}', $model->formatErrors()));
                    return $this->refresh();
                }
            }
        } else {
            return $this->render('create', [
                'model' => $model,
                'category' => $category,
                'cats' => $this->getCats()
            ]);
        }
    }

    public function actionPhotos($id)
    {
        return $this->render('photos', [
            'model' => $this->findModel($id),
        ]);
    }

    private function getCats()
    {
        $result = [];
        foreach (Category::cats() as $cat) {
            if (!count($cat->children) || ArticleModule::setting('itemsInFolder')) {
                $result[$cat->id] = $cat->title;
            }
        }
        return $result;
    }
}

modules/article/views/items/_form.php
<?php
use \nitm\cms\helpers\Image;
use \nitm\cms\modules\article\models\Category;
use \nitm\cms\widgets\DateTimePicker;
use \nitm\cms\widgets\TagsInput;
use yii\helpers\Html;
use yii\helpers\Url;
use kartik\widgets\ActiveForm;
use \nitm\cms\widgets\SeoForm;

$module = $this->context->module->id;
?>
<?php $form = include(\Yii::getAlias("@nitm/cms/views/layouts/form/header.php")); ?>
<?= $form->field($model, 'title') ?>
<?= $form->field($model, 'category_id')->dropDownList($cats) ?>

<?php if ($this->context->module->settings['articleThumb']) : ?>
    <?php if ($model->image_file) : ?>
        <a href="<?= $model->image ?>" class="fancybox"><img src="<?= Image::thumb($model->image_file, 240, 180) ?>"></a>
        <a href="<?= Url::to(['/admin/'.$module.'/items/clear-image', 'id' => $model->primaryKey]) ?>" class="text-danger confirm-delete" title="<?= Yii::t('nitm/cms', 'Clear image')?>"><?= Yii::t('nitm/cms', 'Clear image')?></a>
    <?php endif; ?>
    <?= $form->field($model, 'image_file')->fileInput() ?>
<?php endif; ?>

<?php if ($this->context->module->settings['enableShort']) : ?>
    <?= $form->field($model, 'short')->textarea() ?>
<?php endif; ?>

<?= $form->field($model, 'text')->widget(\nitm\cms\widgets\Redactor::className()) ?>

<?= $form->field($model, 'time')->widget(DateTimePicker::className()); ?>

<?php if ($this->context->module->settings['enableTags']) : ?>
    <?= $form->field($model, 'tagNames')->widget(TagsInput::className()) ?>
<?php endif; ?>

<?php if (IS_ROOT) : ?>
    <?= $form->field($model, 'slug') ?>
    <?= SeoForm::widget(['model' => $model]) ?>
<?php endif; ?>

<?= Html::submitButton(Yii::t('nitm/cms', 'Save'), ['class' => 'btn btn-primary']) ?>
<?php ActiveForm::end(); ?>

modules/article/views/items/_menu.php
<?php
use yii\helpers\Url;
use nitm\helpers\ArrayHelper;

$viewClass = @$viewClass ?: 'nav nav-pills';

$action = ArrayHelper::getValue($this, 'context.action.id', 'index');
$module = ArrayHelper::getValue($this, 'context.module.id', 'article');
?>
<ul class="<?=$viewClass?>">
    <?php if ($action == 'index') : ?>
        <li><a href="<?= Url::to(['/admin/'.$module]) ?>"><i class="fa fa-chevron-left font-12"></i> <?= Yii::t('nitm/cms', 'Categories') ?></a></li>
    <?php endif; ?>
    <li <?= ($action == 'index') ? 'class="active"' : '' ?>><a href="<?= Url::to(['/admin/'.$module.'/items/index', 'id' => $category->primaryKey]) ?>"><?php if ($action != 'index') {
    echo '<i class="fa fa-chevron-left font-12"></i> ';
} ?><?= $category->title ?></a></li>
    <li <?= ($action == 'create') ? 'class="active"' : '' ?>><a href="<?= Url::to(['/admin/'.$module.'/items/form/create', 'id' => $category->primaryKey]) ?>"><?= Yii::t('nitm/cms', 'Add') ?></a></li>
</ul>

modules/article/views/items/_submenu.php
<?php
use \nitm\cms\modules\article\ArticleModule;
use yii\helpers\Url;
use nitm\helpers\ArrayHelper;

$viewClass = @$viewClass ?: 'nav nav-pills';

$action = ArrayHelper::getValue($this, 'context.action.id', 'index');
$module = ArrayHelper::getValue($this, 'context.module.id', 'article');
?>

<ul class="<?=$viewClass?>">
    <li <?= ($action === 'update') ? 'class="active"' : '' ?>><a href="<?= Url::to(['/admin/'.$module.'/items/form/update', 'id' => $model->primaryKey]) ?>"><?= Yii::t('nitm/cms', 'Update article') ?></a></li>
    <?php if (ArticleModule::setting('enablePhotos')) : ?>
        <li <?= ($action === 'photos') ? 'class="active"' : '' ?>><a href="<?= Url::to(['/admin/'.$module.'/items/photos', 'id' => $model->primaryKey]) ?>"><span class="fa fa-camera"></span> <?= Yii::t('nitm/cms', 'Photos') ?></a></li>
    <?php endif; ?>
</ul>

modules/article/views/items/create.php
<?php
$this->title = Yii::t('nitm/cms', 'Create article');
?>
<?= $this->render('_menu', ['category' => $category]) ?>
<?= $this->render('_form', ['model' => $model, 'cats' => $cats]) ?>

modules/article/views/items/edit.php
<?php
$this->title = $model->title;
?>
<?= $this->render('_menu', ['category' => $model->category]) ?>

<?php if($this->context->module->settings['enablePhotos']) echo $this->render('_submenu', ['model' => $model]) ?>

<?= $this->render('_form', ['model' => $model, 'cats' => $cats]) ?>

modules/article/views/items/index.php
<?php
use \nitm\cms\modules\article\models\Item;
use yii\helpers\Html;
use yii\helpers\Url;

$this->title = Yii::t('nitm/cms', 'Articles');

$module = $this->context->module->id;
?>
<?= $this->render('_menu', ['category' => $category]) ?>

<?php if(count($category->items)) : ?>
    <table class="table table-hover">
        <thead>
        <tr>
            <?php if(IS_ROOT) : ?>
                <th width="50">#</th>
            <?php endif; ?>
            <th><?= Yii::t('nitm/cms', 'Title') ?></th>
            <th width="120"><?= Yii::t('nitm/cms', 'Views') ?></th>
            <th width="100"><?= Yii::t('nitm/cms', 'Status') ?></th>
            <th width="120"></th>
        </tr>
        </thead>
        <tbody>
        <?php foreach($category->items as $item) : ?>
            <tr data-id="<?= $item->primaryKey ?>">
                <?php if(IS_ROOT) : ?>
                    <td><?= $item->primaryKey ?></td>
                <?php endif; ?>
                <td><a href="<?= Url::to(['/admin/'.$module.'/items/form/update', 'id' => $item->primaryKey]) ?>"><?= $item->title ?></a></td>
                <td><?= $item->views ?></td>
                <td class="status">
                    <?= Html::checkbox('', $item->status == Item::STATUS_ON, [
                        'class' => 'switch',
                        'data-id' => $item->primaryKey,
                        'data-link' => Url::to(['/admin/'.$module.'/items']),
                    ]) ?>
                </td>
                <td class="text-right">
                    <div class="btn-group btn-group-sm" role="group">
                        <a href="<?= Url::to(['/admin/'.$module.'/items/up', 'id' => $item->primaryKey, 'category_id' => $category->primaryKey]) ?>" class="btn btn-default move-up" title="<?= Yii::t('nitm/cms', 'Move up') ?>"><span class="fa fa-arrow-up"></span></a>
                        <a href="<?= Url::to(['/admin/'.$module.'/items/down', 'id' => $item->primaryKey, 'category_id' => $category->primaryKey]) ?>" class="btn btn-default move-down" title="<?= Yii::t('nitm/cms', 'Move down') ?>"><span class="fa fa-arrow-down"></span></a>
                        <a href="<?= Url::to(['/admin/'.$module.'/items/delete', 'id' => $item->primaryKey]) ?>" class="btn btn-default confirm-delete" title="<?= Yii::t('nitm/cms', 'Delete item') ?>"><span class="fa fa-remove"></span></a>
                    </div>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
<?php else : ?>
    <p><?= Yii::t('nitm/cms', 'No records found') ?></p>
<?php endif; ?>

modules/article/views/items/photos.php
<?php
use \nitm\cms\widgets\Photos;

$this->title = $model->title;
?>

<?= $this->render('_menu', ['category' => $model->category]) ?>
<?= $this->render('_submenu', ['model' => $model]) ?>

<?= Photos::widget(['model' => $model])?>

modules/article/views/items/update.php
<?php
$this->title = $model->title;
?>
<?= $this->render('_menu', ['category' => $model->category]) ?>

<?php if($this->context->module->settings['enablePhotos']) echo $this->render('_submenu', ['model' => $model]) ?>

<?= $this->render('_form', ['model' => $model, 'cats' => $cats]) ?>