modules/categories/controllers/AController.php
<?php

namespace nitm\cms\modules\categories\controllers;

use Yii;
use nitm\cms\components\CategoryController;
use nitm\cms\actions\ChangeStatusAction;
use nitm\cms\actions\ClearImageAction;
use nitm\cms\actions\MoveAction;

class AController extends CategoryController
{
    public $modelClass = 'nitm\cms\modules\categories\models\Category';
    public $categoryClass = 'nitm\cms\modules\categories\models\Category';
    public $moduleName = 'categories';

    public $rootActions = ['fields'];

    //Todo: Remove the slash!
    /** @var string */
    public $viewRoute = '/items';

    public function actions()
    {
        $className = $this->categoryClass;

        return array_merge(parent::actions(), [
            'clear-image' => [
                'class' => ClearImageAction::className(),
                'model' => $className,
            ],
            'on' => [
                'class' => ChangeStatusAction::className(),
                'model' => $className,
            ],
            'off' => [
                'class' => ChangeStatusAction::className(),
                'model' => $className,
            ],
            'up' => [
                'class' => MoveAction::className(),
                'model' => $className,
                'direction' => 'up',
            ],
            'down' => [
                'class' => MoveAction::className(),
                'model' => $className,
                'direction' => 'down',
            ],
        ]);
    }
    /**
     * Create form.
     *
     * @param null $parent
     *
     * @return array|string|\yii\web\Response
     *
     * @throws \yii\web\HttpException
     */
    public function actionCreate($parent = null, $modelCLass = null, $viewOptions = [])
    {
        return parent::actionCreate($parent, $this->categoryClass, $viewOptions);
    }

     /**
      * Update form.
      *
      * @param $id
      *
      * @return array|string|\yii\web\Response
      *
      * @throws \yii\web\HttpException
      */
     public function actionUpdate($id, $modelClass = null, $with = [], $viewOptions = [])
     {
         return parent::actionUpdate($id, $this->categoryClass, $with = [], $viewOptions);
     }

    public function actionForm($type, $id = null, $options = [], $returnData = false)
    {
        switch ($type) {
          case 'create':
           $options['construct'] = [
               'parent_id' => Yii::$app->request->get('parent', null),
            ];
            $id = null;
          break;
       }
        $options = array_merge([
           'view' => $type,
           'action' => \Yii::$app->urlManager->createUrl(array_merge([\Yii::$app->getModule('admin')->id.'/'.$this->module->id.'/'.$this->id.'/'.$type], ['id' => $id])),
        ], $options);

        return parent::actionForm($type, $id, $options, $returnData);
    }

    /**
     * Delete the category by ID.
     *
     * @param $id
     *
     * @return mixed
     */
    public function actionDelete($id, $modelClass = null)
    {
        $this->model = $this->findCategory($id);
        $children = $this->model->children()->all();
        $this->model->deleteWithChildren();
        foreach ($children as $child) {
            $child->afterDelete();
        }

        return [
           true, [
              'action' => 'delete',
           ],
        ];
    }

    public function actionFields($id)
    {
        if (!($model = Category::findOne($id))) {
            return $this->redirect($this->getUrl([$this->module->id]));
        }

        if (Yii::$app->request->post('save')) {
            $fields = Yii::$app->request->post('Field') ?: [];
            $result = [];

            foreach ($fields as $field) {
                $temp = json_decode($field);

                if ($temp === null && json_last_error() !== JSON_ERROR_NONE ||
                    empty($temp->name) ||
                    empty($temp->title) ||
                    empty($temp->type) ||
                    !($temp->name = trim($temp->name)) ||
                    !($temp->title = trim($temp->title)) ||
                    !array_key_exists($temp->type, Category::$fieldTypes)
                ) {
                    continue;
                }
                $options = trim($temp->options);
                if ($temp->type == 'select' || $temp->type == 'checkbox') {
                    if ($options == '') {
                        continue;
                    }
                    $optionsArray = [];
                    foreach (explode(',', $options) as $option) {
                        $optionsArray[] = trim($option);
                    }
                    $options = $optionsArray;
                }

                $result[] = [
                    'name' => \yii\helpers\Inflector::slug($temp->name),
                    'title' => $temp->title,
                    'type' => $temp->type,
                    'options' => $options,
                ];
            }

            $model->fields = $result;

            if ($model->save()) {
                $ids = [];
                foreach ($model->children()->all() as $child) {
                    $ids[] = $child->primaryKey;
                }
                if (count($ids)) {
                    Category::updateAll(['fields' => json_encode($model->fields)], ['in', 'category_id', $ids]);
                }

                $this->flash('success', Yii::t('nitm/cms', 'Category updated'));
            } else {
                $this->flash('error', Yii::t('nitm/cms', 'Update error. {0}', $model->formatErrors()));
            }

            return $this->refresh();
        } else {
            return $this->render('fields', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Change category status.
     *
     * @param $id
     * @param $status
     *
     * @return mixed
     */
    public function changeStatus($id, $status)
    {
        $model = $this->findCategory($id);
        $modelClass = $this->categoryClass;
        $ids = [$model->primaryKey];

        foreach ($model->children()->all() as $child) {
            $ids[] = $child->primaryKey;
        }
        $modelClass::updateAll(['status' => $status], ['in', 'id', $ids]);
        $model->trigger(\yii\db\ActiveRecord::EVENT_AFTER_UPDATE);

        return $this->formatResponse(Yii::t('nitm/cms', 'Status successfully changed'));
    }
}

modules/categories/views/a/_actions.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ButtonDropdown;
use nitm\cms\components\CategoryModel;

?>
<div style="min-width: 204px">
<?= ButtonDropdown::widget([
     'encodeLabel' => false,
     'label' => Html::tag('i', '&nbsp;', [
          'class' => 'fa fa-menu-hamburger',
          'title' => Yii::t('nitm/cms', 'Actions'),
     ]),
     'dropdown' => [
                'encodeLabels' => false,
            'items' => [
            [
                 'label' => Html::tag('i', ' ', [
                      'class' => 'fa fa-pencil font-12',
                 ]).' '.Yii::t('nitm/cms', 'Update'),
                 'url' => $module->getUrl([$this->context->id.'/form/update', 'id' => $model->id]),
            ], [
                 'label' => Html::tag('i', '', [
                      'class' => 'fa fa-plus font-12',
                 ]).' '.Yii::t('nitm/cms', 'Add Sub-Category'),
                 'url' => $module->getUrl([$this->context->id.'/form/create', 'parent' => $model->id]),
            ], [
                 'label' => '',
                 'url' => '#',
                 'options' => [
                      'class' => 'divider',
                      'role' => 'presenation',
                 ],
            ], [
                 'label' => Html::tag('i', '', [
                      'class' => 'fa fa-arrow-up font-12',
                 ]).' '.Yii::t('nitm/cms', 'Move Up'),
                 'url' => $module->getUrl([$this->context->id.'/up', 'id' => $model->id]),
            ], [
                 'label' => Html::tag('i', '', [
                      'class' => 'fa fa-arrow-down font-12',
                 ]).' '.Yii::t('nitm/cms', 'Move Down'),
                 'url' => $module->getUrl([$this->context->id.'/down', 'id' => $model->id]),
            ], [
                 'label' => '',
                 'url' => '#',
                 'options' => [
                      'class' => 'divider',
                      'role' => 'presenation',
                 ],
            ], [
                 'label' => Html::tag('i', '', [
                      'class' => 'fa fa-eye-close font-12',
                 ]).' '.Yii::t('nitm/cms', 'Turn Off'),
                 'url' => $module->getUrl([$this->context->id.'/on', 'id' => $model->id]),
                 'visible' => $model->status == CategoryModel::STATUS_OFF,
            ], [
                 'label' => Html::tag('i', '', [
                      'class' => 'fa fa-eye-open font-12',
                 ]).' '.Yii::t('nitm/cms', 'Turn On'),
                 'url' => $module->getUrl([$this->context->id.'/off', 'id' => $model->id]),
                 'visible' => $model->status == CategoryModel::STATUS_ON,
            ], [
                 'label' => Html::tag('i', '', [
                      'class' => 'fa fa-remove font-12',
                 ]).' '.Yii::t('nitm/cms', 'Delete Category'),
                 'url' => $module->getUrl([$this->context->id.'/delete', 'id' => $model->id]),
                 'linkOptions' => [
                      'role' => 'metaAction deleteAction',
                 ],
            ],
         ],
     ],
]) ?>
</div>

modules/categories/views/a/_category.php
<?php

use yii\helpers\Html;
use nitm\cms\components\CategoryModel;
use yii\widgets\ListView;

$module = $this->context->module;
$wrapper = isset($wrapper) ? $wrapper : true;
$children = $model->isRelationPopulated('children') ? $model->children : [];
?>
<?php if ($wrapper): ?>
<li class="list-group-item <?= count($model->children) ? 'list-group-item-info' : '' ?>" style="overflow: visible; position: static;z-index: 1">
<?php endif; ?>
	<div class="media-left media-top">
		<h4 style="width: 64px;"><?= $model->id ?></h4>
	</div>
	<div class="media-body" style="overflow-y: visible">
		<?php if (!count($children) || !empty(Yii::$app->controller->module->settings['itemsInFolder'])) : ?>
		  <h4 style="display: flex; justify-content: space-between; align-items: center;">
				<a href="<?= $module->getUrl(['categories/items', 'id' => $model->id]) ?>" <?= ($model->status == CategoryModel::STATUS_OFF ? 'class="smooth"' : '') ?>>
	  				<?= $model->title() ?>
				</a>
				<?= $this->render('_actions', [
                  'module' => $this->context->module,
                  'model' => $model,
                ]); ?>
			</h4>
		 <?php else : ?>
			  <h4 <?= ($model->status == CategoryModel::STATUS_OFF ? 'class="smooth"' : '') ?> style="display: flex; justify-content: space-between; align-items: center;">
				  <span class="button">
					  <i class="caret"></i>
					  <?= Html::a($model->title().' '.Html::tag('span', ' Show '.count($children).' Children', [
                           'class' => 'badge'
                       ]), '#', [
                           'role' => 'visibility',
                           'data-id' => 'sub-categories'.$model->id,
                   ])?>
					</span>
					<?= $this->render('_actions', [
                      'module' => $this->context->module,
                      'model' => $model,
                   ]); ?>
			  </h4>
			  <div class="hidden" id="sub-categories<?=$model->id?>">
				<?= ListView::widget([
                     'layout' => "{items}\n{pager}",
                     'dataProvider' => new \yii\data\ArrayDataProvider(['allModels' => $children]),
                     'itemView' => '_category',
                     'itemOptions' => [
                         'tag' => 'div',
                         'class' => 'media',
                         'style' => 'overflow: visible',
                    ],
                    'options' => [
                      'tag' => false,
                    ],
                    'viewParams' => [
                        'wrapper' => false,
                    ],
                ]); ?>
			</div>
		<?php endif; ?>
	</div>
<?php if ($wrapper): ?>
</li>
<?php endif; ?>

modules/categories/views/a/_form.php
<?php
use nitm\cms\widgets\TagsInput;
use yii\helpers\Html;
use kartik\widgets\ActiveForm;
use kartik\widgets\Select2;
use nitm\cms\widgets\SeoForm;

$class = $this->context->categoryClass;
$settings = $this->context->module->settings;

?>
<?php $form = include \Yii::getAlias('@nitm/cms/views/layouts/form/header.php'); ?>
<?= $form->field($model, 'title') ?>
<?= $form->field($model, 'description')->textArea() ?>

<?= $form->field($model, 'parent_id')->widget(Select2::class, [
   'options' => [
      'encode' => false,
      'encodeSpaces' => false,
   ],
   'data' => (new $class())->getNestedList(),
   'pluginOptions' => [
      'escapeMarkup ' => 'function(markup) {return markup;}',
   ],
])->label(Yii::t('nitm/cms', 'Parent category')); ?>

<?php if (!empty($settings['categoryThumb'])) : ?>
    <?= \nitm\filemanager\widgets\ImageUpload::widget([
      'model' => $model->image(),
      ]) ?>
<?php endif; ?>

<?php if (!empty($settings['categoryTags'])) : ?>
    <?= $form->field($model, 'tagNames')->widget(TagsInput::className()) ?>
<?php endif; ?>

<!-- <?php if (IS_ROOT) : ?>
    <?= $form->field($model, 'slug') ?>
    <?php if (isset($model->attributes['cache'])) : ?>
        <?= $form->field($model, 'cache')->checkbox() ?>
    <?php endif; ?>
    <?= SeoForm::widget(['model' => $model]) ?>
<?php endif; ?> -->

<?= Html::submitButton(Yii::t('nitm/cms', 'Save'), ['class' => 'btn btn-primary']) ?>
<?php ActiveForm::end(); ?>

modules/categories/views/a/_menu.php
<?php
use yii\helpers\Url;
use yii\helpers\ArrayHelper;

$action = $this->context->action->id;
$viewClass = @$viewClass ?: 'nav nav-pills';

$action = ArrayHelper::getValue($this, 'context.action.id', 'index');
$module = ArrayHelper::getValue($this, 'context.module.id', 'location');
?>
 <ul class="<?=$viewClass?>">
     <li <?= ($action === 'index') ? 'class="active"' : '' ?>>
         <a href="<?= $this->context->getReturnUrl($module) ?>">
             <?php if ($action === 'update') : ?>
                 <i class="fa fa-chevron-left font-12"></i>
             <?php endif; ?>
             <?= Yii::t('nitm/cms', 'List') ?>
         </a>
     </li>
     <li <?= ($action === 'create') ? 'class="active"' : '' ?>><a href="<?= Url::to($this->context->getUrl($module.'/a/form/create')) ?>"><?= Yii::t('nitm/cms', 'Create') ?></a></li>
 </ul>

modules/categories/views/a/_submenu.php
<?php
use yii\helpers\Url;
use nitm\helpers\ArrayHelper;

$viewClass = @$viewClass ?: 'nav nav-pills';

$action = ArrayHelper::getValue($this, 'context.action.id', 'index');
$module = ArrayHelper::getValue($this, 'context.module.id', 'categories');
?>
<?php if (IS_ROOT) : ?>
    <ul class="<?=$viewClass?>">
        <li <?= ($action === 'update') ? 'class="active"' : '' ?>><a href="<?= Url::to(['/admin/'.$module.'/a/form/update', 'id' => $model->primaryKey]) ?>"><?= Yii::t('nitm/cms', 'Update') ?></a></li>
        <li <?= ($action === 'fields') ? 'class="active"' : '' ?>><a href="<?= Url::to(['/admin/'.$module.'/a/fields', 'id' => $model->primaryKey]) ?>"><span class="fa fa-cog"></span> <?= Yii::t('nitm/cms', 'Fields') ?></a></li>
    </ul>

<?php endif;?>

modules/categories/views/a/create.php
<?php
$this->title = Yii::t('nitm/cms', 'Create category');
?>
<?= $this->render('_menu') ?>
<?= $this->render('_form', ['model' => $model]) ?>

modules/categories/views/a/edit.php
<?php
$this->title = Yii::t('nitm/cms', 'Edit category');
?>
<?= $this->render('_menu') ?>

<?php if(!empty($this->params['submenu'])) echo $this->render('_submenu', ['model' => $model], $this->context); ?>
<?= $this->render('_form', ['model' => $model]) ?>

modules/categories/views/a/fields.php
<?php
use yii\helpers\Html;
use \nitm\cms\modules\categories\assets\FieldsAsset;
use \nitm\cms\modules\categories\models\Category;

$this->title = Yii::t('nitm/cms', 'Category fields');

$this->registerAssetBundle(FieldsAsset::className());

$this->registerJs('
var fieldTemplate = \'\
    <tr>\
        <td>'. Html::input('text', null, null, ['class' => 'form-control field-name']) .'</td>\
        <td>'. Html::input('text', null, null, ['class' => 'form-control field-title']) .'</td>\
        <td>\
            <select class="form-control field-type">'.str_replace("\n", "", Html::renderSelectOptions('', Category::$fieldTypes)).'</select>\
        </td>\
        <td><textarea class="form-control field-options" placeholder="'.Yii::t('nitm/cms', 'Type options with `comma` as delimiter').'" style="display: none;"></textarea></td>\
        <td class="text-right">\
            <div class="btn-group btn-group-sm" role="group">\
                <a href="#" class="btn btn-default move-up" title="'. Yii::t('nitm/cms', 'Move up') .'"><span class="fa fa-arrow-up"></span></a>\
                <a href="#" class="btn btn-default move-down" title="'. Yii::t('nitm/cms', 'Move down') .'"><span class="fa fa-arrow-down"></span></a>\
                <a href="#" class="btn btn-default color-red delete-field" title="'. Yii::t('nitm/cms', 'Delete item') .'"><span class="fa fa-remove"></span></a>\
            </div>\
        </td>\
    </tr>\';
', \yii\web\View::POS_HEAD);

?>
<?= $this->render('@nitm/cms/views/category/_menu') ?>
<?= $this->render('_submenu', ['model' => $model]) ?>
<br>

<?= Html::button('<i class="fa fa-plus font-12"></i> '.Yii::t('nitm/cms', 'Add field'), ['class' => 'btn btn-default', 'id' => 'addField']) ?>

<table id="categoryFields" class="table table-hover">
    <thead>
        <th>Name</th>
        <th><?= Yii::t('nitm/cms', 'Title') ?></th>
        <th><?= Yii::t('nitm/cms', 'Type') ?></th>
        <th><?= Yii::t('nitm/cms', 'Options') ?></th>
        <th width="120"></th>
    </thead>
    <tbody>
    <?php foreach($model->fields as $field) : ?>
        <tr>
            <td><?= Html::input('text', null, $field->name, ['class' => 'form-control field-name']) ?></td>
            <td><?= Html::input('text', null, $field->title, ['class' => 'form-control field-title']) ?></td>
            <td>
                <select class="form-control field-type">
                    <?= Html::renderSelectOptions($field->type, Category::$fieldTypes) ?>
                </select>
            </td>
            <td>
                <textarea class="form-control field-options" placeholder="<?= Yii::t('nitm/cms', 'Type options with `comma` as delimiter') ?>" <?= (!$field->options && $field->type != 'file') ? 'style="display: none;"' : '' ?> ><?= is_array($field->options) ? implode(',', $field->options) : $field->options ?></textarea>
            </td>
            <td class="text-right">
                <div class="btn-group btn-group-sm" role="group">
                    <a href="#" class="btn btn-default move-up" title="<?= Yii::t('nitm/cms', 'Move up') ?>"><span class="fa fa-arrow-up"></span></a>
                    <a href="#" class="btn btn-default move-down" title="<?= Yii::t('nitm/cms', 'Move down') ?>"><span class="fa fa-arrow-down"></span></a>
                    <a href="#" class="btn btn-default color-red delete-field" title="<?= Yii::t('nitm/cms', 'Delete item') ?>"><span class="fa fa-remove"></span></a>
                </div>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
<?= Html::button('<i class="fa fa-ok"></i> '.Yii::t('nitm/cms', 'Save fields'), ['class' => 'btn btn-primary', 'id' => 'saveCategoryBtn']) ?>

modules/categories/views/a/index.php
<?php
/**
 * @var \yii\web\View
 */
use yii\widgets\ListView;

\yii\bootstrap\BootstrapPluginAsset::register($this);
$this->title = Yii::$app->getModule('admin')->activeModules[$this->context->module->id]->title;
?>

<?= $this->render('_menu') ?>
<br>
<?= ListView::widget([
    'layout' => "{items}\n{pager}",
    'dataProvider' => $dataProvider,
    'itemView' => '_category',
    'itemOptions' => [
      'tag' => false,
    ],
    'options' => [
      'class' => 'media-list list-group',
      'tag' => 'ul',
   ],
]);
?>

modules/categories/views/a/update.php
<?php
$this->title = Yii::t('nitm/cms', 'Update category');
?>
<?= $this->render('_menu') ?>

<?php if (!empty($this->params['submenu'])) {
    echo $this->render('_submenu', ['model' => $model], $this->context);
} ?>
<?= $this->render('_form', ['model' => $model]) ?>