modules/feedback/models/Feedback.php
<?php
namespace nitm\cms\modules\feedback\models;

use Yii;
use nitm\cms\behaviors\CalculateNotice;
use \nitm\cms\helpers\Mail;
use nitm\cms\models\Setting;
use nitm\cms\modules\feedback\FeedbackModule;
use nitm\cms\validators\ReCaptchaValidator;
use nitm\validators\EscapeValidator;
use yii\helpers\Url;

class Feedback extends \nitm\cms\db\ActiveRecord
{
    const STATUS_NEW = 0;
    const STATUS_VIEW = 1;
    const STATUS_ANSWERED = 2;

    const FLASH_KEY = 'eaysiicms_feedback_send_result';

    public $reCaptcha;

    public static function tableName()
    {
        return 'cms_feedback';
    }

    public function rules()
    {
        return [
            [['name', 'email', 'text'], 'required'],
            [['name', 'email', 'phone', 'title', 'text'], 'trim'],
            [['name','title', 'text'], EscapeValidator::className()],
            ['title', 'string', 'max' => 128],
            ['email', 'email'],
            ['phone', 'match', 'pattern' => '/^[\d\s-\+\(\)]+$/'],
            ['reCaptcha', ReCaptchaValidator::className(), 'when' => function ($model) {
                return $model->isNewRecord && FeedbackModule::setting('enableCaptcha');
            }],
        ];
    }

    public function beforeSave($insert)
    {
        if (parent::beforeSave($insert)) {
            if ($insert) {
                $this->ip = Yii::$app->request->userIP;
                $this->time = time();
                $this->status = self::STATUS_NEW;
            }
            return true;
        } else {
            return false;
        }
    }

    public function afterSave($insert, $changedAttributes)
    {
        parent::afterSave($insert, $changedAttributes);

        if ($insert) {
            $this->mailAdmin();
        }
    }

    public function attributeLabels()
    {
        return [
            'email' => 'E-mail',
            'name' => Yii::t('nitm/cms', 'Name'),
            'title' => Yii::t('nitm/cms', 'Title'),
            'text' => Yii::t('nitm/cms', 'Text'),
            'answer_subject' => Yii::t('nitm/cms', 'Subject'),
            'answer_text' => Yii::t('nitm/cms', 'Text'),
            'phone' => Yii::t('nitm/cms', 'Phone'),
            'reCaptcha' => Yii::t('nitm/cms', 'Anti-spam check')
        ];
    }

    public function behaviors()
    {
        return [
            'cn' => [
                'class' => CalculateNotice::className(),
                'callback' => function () {
                    return self::find()->status(self::STATUS_NEW)->count();
                }
            ]
        ];
    }

    public function mailAdmin()
    {
        if (!FeedbackModule::setting('mailAdminOnNewFeedback')) {
            return false;
        }
        return Mail::send(
            Setting::get('admin_email'),
            FeedbackModule::setting('subjectOnNewFeedback'),
            FeedbackModule::setting('templateOnNewFeedback'),
            ['feedback' => $this, 'link' => Url::to($this->context->getUrl(['/admin/feedback/a/view', 'id' => $this->primaryKey]), true)]
        );
    }

    public function sendAnswer()
    {
        return Mail::send(
            $this->email,
            $this->answer_subject,
            FeedbackModule::setting('answerTemplate'),
            ['feedback' => $this],
            ['replyTo' => Setting::get('admin_email')]
        );
    }
}

modules/feedback/controllers/AController.php
<?php
namespace nitm\cms\modules\feedback\controllers;

use Yii;
use yii\data\ActiveDataProvider;
use \nitm\cms\actions\DeleteAction;
use \nitm\cms\components\Controller;
use \nitm\cms\models\Setting;
use \nitm\cms\modules\feedback\models\Feedback;

class AController extends Controller
{
    public $modelClass = 'nitm\cms\modules\feedback\models\Feedback';
    public $new = 0;
    public $noAnswer = 0;

    public function actions()
    {
        return [
            'delete' => [
                'class' => DeleteAction::className(),
                'successMessage' => Yii::t('nitm/cms', 'Feedback deleted')
            ]
        ];
    }

    public function init()
    {
        parent::init();

        $this->new = Yii::$app->getModule('admin')->activeModules['feedback']->notice;
        $this->noAnswer = Feedback::find()->status(Feedback::STATUS_VIEW)->count();
    }

    public function actionIndex($className=null, $options=[])
    {
        $data = new ActiveDataProvider([
            'query' => Feedback::find()->status(Feedback::STATUS_NEW)->asc(),
        ]);
        return $this->render('index', [
            'data' => $data
        ]);
    }

    public function actionNoanswer()
    {
        $this->setReturnUrl();

        $data = new ActiveDataProvider([
            'query' => Feedback::find()->status(Feedback::STATUS_VIEW)->asc(),
        ]);
        return $this->render('index', [
            'data' => $data
        ]);
    }

    public function actionAll()
    {
        $this->setReturnUrl();

        $data = new ActiveDataProvider([
            'query' => Feedback::find()->desc(),
        ]);
        return $this->render('index', [
            'data' => $data
        ]);
    }

    public function actionView($id, $modelClass=null, $options=[])
    {
        $model = $this->findModel($id);

        if ($model->status == Feedback::STATUS_NEW) {
            $model->status = Feedback::STATUS_VIEW;
            $model->update();
        }

        $postData = Yii::$app->request->post('Feedback');
        if ($postData) {
            if (filter_var(Setting::get('admin_email'), FILTER_VALIDATE_EMAIL)) {
                $model->answer_subject = filter_var($postData['answer_subject'], FILTER_SANITIZE_STRING);
                $model->answer_text = filter_var($postData['answer_text'], FILTER_SANITIZE_STRING);
                if ($model->sendAnswer()) {
                    $model->status = Feedback::STATUS_ANSWERED;
                    $model->save();
                    $this->flash('success', Yii::t('nitm/cms', 'Answer successfully sent'));
                } else {
                    $this->flash('error', Yii::t('nitm/cms', 'An error has occurred while sending mail'));
                }
            } else {
                $this->flash('error', Yii::t('nitm/cms', 'Please fill correct `Admin E-mail` in Settings'));
            }

            return $this->refresh();
        } else {
            if (!$model->answer_text) {
                $model->answer_subject = Yii::t('nitm/cms', $this->module->settings['answerSubject']);
                if ($this->module->settings['answerHeader']) {
                    $model->answer_text = Yii::t('nitm/cms', $this->module->settings['answerHeader']) . " " . $model->name . ".\n";
                }
                if ($this->module->settings['answerFooter']) {
                    $model->answer_text .= "\n\n" . Yii::t('nitm/cms', $this->module->settings['answerFooter']);
                }
            }

            return $this->render('view', [
                'model' => $model
            ]);
        }
    }

    public function actionSetAnswer($id)
    {
        $model = $this->findModel($id);

        $model->status = Feedback::STATUS_ANSWERED;
        if ($model->update()) {
            $this->flash('success', Yii::t('nitm/cms', 'Feedback updated'));
        } else {
            $this->flash('error', Yii::t('nitm/cms', 'Update error. {0}', $model->formatErrors()));
        }
        return $this->back();
    }
}

modules/feedback/controllers/SendController.php
<?php
namespace nitm\cms\modules\feedback\controllers;

use Yii;
use \nitm\cms\modules\feedback\models\Feedback as FeedbackModel;

class SendController extends \yii\web\Controller
{
    public function actionIndex($className=null, $options=[])
    {
        $model = new FeedbackModel;

        $request = Yii::$app->request;

        if ($model->load($request->post())) {
            $returnUrl = $model->save() ? $request->post('successUrl') : $request->post('errorUrl');
            return $this->redirect($returnUrl);
        } else {
            return $this->redirect(Yii::$app->request->baseUrl);
        }
    }
}

modules/feedback/views/a/_menu.php
<?php
use yii\helpers\Url;
use nitm\helpers\ArrayHelper;

$viewClass = @$viewClass ?: 'nav nav-pills';

$action = ArrayHelper::getValue($this, 'context.action.id', 'index');
$module = ArrayHelper::getValue($this, 'context.module.id', 'feedback');

$viewClass = @$viewClass ?: 'nav nav-pills';

$backTo = null;
$indexUrl = Url::to(['/admin/'.$module]);
$noanswerUrl = Url::to(['/admin/'.$module.'/a/noanswer']);
$allUrl = Url::to(['/admin/'.$module.'/a/all']);

if ($action === 'view') {
    $returnUrl = $this->context->getReturnUrl($indexUrl);

    if (strpos($returnUrl, 'noanswer') !== false) {
        $backTo = 'noanswer';
        $noanswerUrl = $returnUrl;
    } elseif (strpos($returnUrl, 'all') !== false) {
        $backTo = 'all';
        $allUrl = $returnUrl;
    } else {
        $backTo = 'index';
        $indexUrl = $returnUrl;
    }
}
?>
<ul class="<?=$viewClass?>">
    <li <?= ($action === 'index') ? 'class="active"' : '' ?>>
        <a href="<?= $indexUrl ?>">
            <?php if ($backTo === 'index') : ?>
                <i class="fa fa-chevron-left font-12"></i>
            <?php endif; ?>
            <?= Yii::t('nitm/cms', 'New') ?>
            <?php if (ArrayHelper::getValue($this, 'context.new') > 0) : ?>
                <span class="badge"><?= ArrayHelper::getValue($this, 'context.new') ?></span>
            <?php endif; ?>
        </a>
    </li>
    <li <?= ($action === 'noanswer') ? 'class="active"' : '' ?>>
        <a href="<?= $noanswerUrl ?>">
            <?php if ($backTo === 'noanswer') : ?>
                <i class="fa fa-chevron-left font-12"></i>
            <?php endif; ?>
            <?= Yii::t('nitm/cms', 'No answer') ?>
            <?php if (ArrayHelper::getValue($this, 'context.noAnswer') > 0) : ?>
                <span class="badge"><?= ArrayHelper::getValue($this, 'context.noAnswer') ?></span>
            <?php endif; ?>
        </a>
    </li>
    <li <?= ($action === 'all') ? 'class="active"' : '' ?>>
        <a href="<?= $allUrl ?>">
            <?php if ($backTo === 'all') : ?>
                <i class="fa fa-chevron-left font-12"></i>
            <?php endif; ?>
            <?= Yii::t('nitm/cms', 'All') ?>
        </a>
    </li>
    <?php if ($action === 'view' && isset($noanswer) && !$noanswer) : ?>
        <li class="pull-right">
            <a href="<?= Url::to(['/admin/'.$module.'/a/set-answer', 'id' => Yii::$app->request->get('id')]) ?>" class="text-warning"><span class="fa fa-ok"></span> <?= Yii::t('nitm/cms', 'Mark as answered') ?></a>
        </li>
    <?php endif; ?>
</ul>

modules/feedback/views/a/index.php
<?php
use yii\helpers\StringHelper;
use yii\helpers\Url;
use \nitm\cms\modules\feedback\models\Feedback;

$this->title = Yii::t('nitm/cms', 'Feedback');
$module = $this->context->module->id;
?>

<?= $this->render('_menu') ?>

<?php if ($data->count > 0) : ?>
    <table class="table table-hover">
        <thead>
            <tr>
                <?php if (IS_ROOT) : ?>
                    <th width="50">#</th>
                <?php endif; ?>
                <th><?= Yii::t('nitm/cms', $this->context->module->settings['enableTitle'] ? 'Title' : 'Text') ?></th>
                <th width="150"><?= Yii::t('nitm/cms', 'Date') ?></th>
                <th width="100"><?= Yii::t('nitm/cms', 'Answer') ?></th>
                <th width="30"></th>
            </tr>
        </thead>
        <tbody>
    <?php foreach ($data->models as $item) : ?>
            <tr>
                <?php if (IS_ROOT) : ?>
                    <td><?= $item->primaryKey ?></td>
                <?php endif; ?>
                <td>
                    <a href="<?= Url::to($this->context->getUrl([$module.'/a/view', 'id' => $item->primaryKey])) ?>">
                        <?= ($this->context->module->settings['enableTitle'] && $item->title != '') ? $item->title : StringHelper::truncate($item->text, 64, '...')?>
                    </a>
                </td>
                <td><?= Yii::$app->formatter->asDatetime($item->time, 'short') ?></td>
                <td>
                    <?php if ($item->status == Feedback::STATUS_ANSWERED) : ?>
                        <span class="text-success"><?= Yii::t('nitm/cms', 'Yes') ?></span>
                    <?php else : ?>
                        <span class="text-danger"><?= Yii::t('nitm/cms', 'No') ?></span>
                    <?php endif; ?>
                </td>
                <td><a href="<?= Url::to($this->context->getUrl([$module.'/a/delete', 'id' => $item->primaryKey])) ?>" class="fa fa-remove confirm-delete" title="<?= Yii::t('nitm/cms', 'Delete item') ?>"></a></td>
            </tr>
    <?php endforeach; ?>
        </tbody>
    </table>
    <?= yii\widgets\LinkPager::widget([
        'pagination' => $data->pagination
    ]) ?>
<?php else : ?>
    <p><?= Yii::t('nitm/cms', 'No records found') ?></p>
<?php endif; ?>

modules/feedback/views/a/view.php
<?php
use yii\helpers\Html;
use \nitm\cms\modules\feedback\models\Feedback;
use yii\widgets\ActiveForm;

$this->title = Yii::t('nitm/cms', 'View feedback');
$this->registerCss('.feedback-view dt{margin-bottom: 10px;}');

if($model->status == Feedback::STATUS_ANSWERED) {
    $this->registerJs('$(".send-answer").click(function(){return confirm("'.Yii::t('nitm/cms', 'Are you sure you want to resend the answer?').'");})');
}
?>
<?= $this->render('_menu', ['noanswer' => $model->status == Feedback::STATUS_ANSWERED]) ?>

<dl class="dl-horizontal feedback-view">
    <dt><?= Yii::t('nitm/cms', 'Name') ?></dt>
    <dd><?= $model->name ?></dd>

    <dt>E-mail</dt>
    <dd><?= $model->email ?></dd>

    <?php if($this->context->module->settings['enablePhone']) : ?>
    <dt><?= Yii::t('nitm/cms', 'Phone') ?></dt>
    <dd><?= $model->phone ?></dd>
    <?php endif; ?>

    <?php if($this->context->module->settings['enableTitle']) : ?>
    <dt><?= Yii::t('nitm/cms', 'Title') ?></dt>
    <dd><?= $model->title ?></dd>
    <?php endif; ?>

    <dt>IP</dt>
    <dd><?= $model->ip ?> <a href="//freegeoip.net/?q=<?= $model->ip ?>" class="label label-info" target="_blank">info</a></dd>

    <dt><?= Yii::t('nitm/cms', 'Date') ?></dt>
    <dd><?= Yii::$app->formatter->asDatetime($model->time, 'medium') ?></dd>

    <dt><?= Yii::t('nitm/cms', 'Text') ?></dt>
    <dd><?= nl2br($model->text) ?></dd>
</dl>

<hr>
<h2><small><?= Yii::t('nitm/cms', 'Answer') ?></small></h2>

<?php $form = ActiveForm::begin() ?>
    <?= $form->field($model, 'answer_subject') ?>
    <?= $form->field($model, 'answer_text')->textarea(['style' => 'height: 250px']) ?>
    <?= Html::submitButton(Yii::t('nitm/cms', 'Send'), ['class' => 'btn btn-success send-answer']) ?>
<?php ActiveForm::end() ?>